/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// populate examples from examples folder. Only include .mdx and .md files
const fs = require("fs");

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// get examples from the file called examples-toc.json

const examples = JSON.parse(fs.readFileSync("./docusaurus/examples-toc.json", "utf8")).find(x => x.label === "Examples");

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docsSidebar: [
        // {
        //   type: "category",
        //   label: "Getting Started",
        //   collapsed: false,
        //   collapsible: false,
        //   items: [
        //     // "guardrails_ai/introduction",
        //     "guardrails_ai/installation",
        //     "guardrails_ai/getting_started"
        //   ],
        // },
        {
          type: "doc",
          label: "Guardrails AI",
          id: "index"
        },
        {
          type: "category",
          label: "Defining Guardrails",
          items: [
            {
              type: "autogenerated",
              dirName: "defining_guards"
            }
          ]
        },
        // {
        //   type: "category",
        //   label: "Concepts",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "concepts"
        //     }
        //   ]
        // },
        // {
        //   type: "doc",
        //   id: "faq",
        //   label: "Validator Library"
        // },
        // {
        //   type: "doc",
        //   id: "0-2-migration",
        //   label: "Migrating to 0.2x"
        // },
        // {
        //   type: "category",
        //   label: "API Reference",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "api_reference_markdown/markdown"
        //     }
        //   ]
        // },
        // {
        //   type: "doc",
        //   id: "faq",
        //   label: "FAQ"
        // },
        examples,
        // {
        //   type: "category",
        //   label: "Integrations",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "integrations"
        //     }
        //   ]
        // }
  ]
};

module.exports = sidebars;
