name: Build Guardrails Server Image
description: Build and optionally push the Guardrails server container image.

inputs:
  context:
    description: Build context
    required: false
    default: .
  dockerfile:
    description: Path to Dockerfile
    required: false
    default: server_ci/Dockerfile

  tags:
    description: Newline-separated image tags
    required: true
  platforms:
    description: Comma-separated platforms for buildx
    required: true

  push:
    description: Whether to push images
    required: false
    default: "false"
  load:
    description: Whether to load image into local docker (single-platform only)
    required: false
    default: "false"

  python_version:
    description: Python version (e.g., 3.12)
    required: true
  variant:
    description: Base image variant (e.g., slim)
    required: true

  guardrails_extensions:
    description: Comma-separated list of hub extensions to install in the image
    required: false
    default: ""

  version:
    description: Version label to bake into the image
    required: true
  commit:
    description: Git commit SHA to bake into the image
    required: true
  build_date:
    description: Build timestamp (RFC3339)
    required: false
    default: ""

  oci_source:
    description: OCI source label
    required: true
  oci_vendor:
    description: OCI vendor label
    required: true
  oci_authors:
    description: OCI authors label
    required: true

  guardrails_token:
    description: Guardrails Hub token (used when guardrails_extensions is set)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Compute build date
      shell: bash
      run: |
        set -euo pipefail
        if [ -n "${{ inputs.build_date }}" ]; then
          echo "BUILD_DATE=${{ inputs.build_date }}" >> "$GITHUB_ENV"
        else
          echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"
        fi

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          PYTHON_VERSION=${{ inputs.python_version }}
          VARIANT=${{ inputs.variant }}
          GUARDRAILS_EXTENSIONS=${{ inputs.guardrails_extensions }}
          VERSION=${{ inputs.version }}
          COMMIT=${{ inputs.commit }}
          BUILD_DATE=${{ env.BUILD_DATE }}
          OCI_SOURCE=${{ inputs.oci_source }}
          OCI_VENDOR=${{ inputs.oci_vendor }}
          OCI_AUTHORS=${{ inputs.oci_authors }}
        secrets: ${{ inputs.guardrails_token != '' && format('guardrails_token={0}', inputs.guardrails_token) || '' }}
