# flake8: noqa
"""This module contains the constants and utils used by the validator.py."""


PROVENANCE_V1_PROMPT = """Instruction:
As an Attribution Validator, you task is to verify whether the following contexts support the claim:

Claim:
{}

Contexts:
{}

Just respond with a "Yes" or "No" to indicate whether the given contexts support the claim.
Response:"""

SENSITIVE_WORDS_MAP = {
    "is adopted": "was adopted",
    "adoptive parent": "parent",
    "grandfather clause": "legacy",
    "poor": "lower-income",
    "blue-collar": "lower-income",
    "low-class people": "people experiencing socioeconomic difficulty",
    "welfare-reliant": "people receiving government assistance",
    "up-and-coming neighborhood": "gentrified neighborhood",
    "normal body": "non-disabled body",
    "geezer": "older person",
    "geriatric": "elderly",
    "retarded": "person with a learning disability",
    "addicts": "people with an addiction",
    "disabled community": "disability community",
    "disabled sport": "sport for athletes with a disability",
    "birth defect": "congenital disability",
    "downs person": "person who has down syndrome",
    "mongoloid": "person who has down syndrome",
    "autistic": "a person on the autism spectrum",
    "quadriplegic": "a person with quadriplegia",
    "paraplegic": "a person with paraplegia",
    "epileptic": "a person with epilepsy",
    "a dwarf": "a person of short stature",
    "a midget": "a person of short stature",
    "learning disability": "learning difference",
    "slow learner": "person with a learning disability",
    "hearing-impaired": "deaf",
    "brain damaged": "a person with a brain injury",
    "sanity check": "quick check",
    "special-ed students": "students who receive special education services",
    "special education students": "students who receive special education services",
    "handicapped parking": "accessible parking",
    "handicapped bathrooms": "accessible bathrooms",
    "gender identity disorder": "gender dysphoria",
    "hermaphrodite": "intersex",
    "opposite sex": "LGBTQ+ community",
    "special rights": "equal protection",
    "actress": "actor",
    "businessman": "business person",
    "busboy": "busser",
    "anchorman": "anchor",
    "caveman": "cave dweller",
    "congressman": "congressperson",
    "countryman": "fellow citizen",
    "craftsman": "artisan",
    "crewman": "crew member",
    "doorman": "door attendant",
    "fireman": "firefighter",
    "fisherman": "angler",
    "forefather": "ancestor",
    "foreman": "supervisor",
    "gentleman": "person",
    "man": "individual",
    "man hours": "engineer hours",
    "mankind": "humanity",
    "the common man": "folks",
    "chairman": "head",
    "mailman": "postal worker",
    "policeman": "police officer",
    "females": "women",
    "sexual preference": "sexual orientation",
    "eskimo": "alaska native",
    "hapa": "pacific islander",
    "blacklist": "blocklist",
    "whitelist": "allowlist",
    "mulatto": "mixed race",
    "undocumented": "non-citizen(s)",
    "slavin'": "working hard",
    "killed it": "did well",
    "libtard": "liberal",
    "feminazi": "feminist",
    "tree-hugger": "environmentalist",
    "woke": "liberal",
    "wokerati": "liberal people",
    "antifa": "anti-fascist",
    "maternity leave": "parental leave",
    "paternity leave": "parental leave",
    "alcoholic": "person with an alcohol use disorder",
    "smoker": "person who smokes",
    "homeless": "person without housing",
    "prostitute": "sex worker",
    "underweight": "lower weight",
    "overweight": "higher weight",
    "birth sex": "assigned sex",
    "committed suicide": "died by suicide",
    "crazy": "chaotic",
    "insane": "chaotic",
    "gyp": "cheat",
    "manpower": "resources",
    "manning": "staffing",
    "off the reservation": "outside of normal behavior",
    "paddy wagon": "police van",
    "rule of thumb": "general guideline",
}
