name: Release PyPi Version

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.13.x

      - name: Poetry cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
        with:
          version: 2.1.1

      - name: Install dependencies
        run: make full

      - name: Upload to PyPI
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish --build -u __token__ -p $PYPI_PASSWORD
